spring:
  datasource:
    username: root
    password: 88571679
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 5000
      min-idle: 5
      max-wait: 60000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100
    lettuce:
      pool:
        max-active: 100
        max-wait: 10
        max-idle: 10
        min-idle: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 10
        max-wait: 10000
  application:
    name: rabbitmq-springboot
  rabbitmq:
    host: 192.168.237.4
    port: 5672
    virtual-host: ems
    username: ems
    password: ems
    listener:
      simple:
        concurrency: 20
        max-concurrency: 50
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        max-interval: 20000
        multiplier: 1


mybatis:
  type-aliases-package: com.zyq.demo.entity
  mapper-locations: classpath:mapper/*.xml

